name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        run: sudo apt-get update && sudo apt-get install --yes gcc jq
      - name: Validate suite
        run: ./test.sh
